# Generated by Django 3.2.5 on 2021-08-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tanggal',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='deskripsi',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='judul',
            new_name='tittle',
        ),
    ]
